# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0296e23dca205888bb8e6c6cf7022b8797eed7a7ea4cc011528219535f2f5e36a352fba9b26e09bdd6c5c8fbbfb5e6bd4da93f8d7a64c9aac1304d49fdfbdc6c

test:
  secret_key_base: e40443b82baa39fc9ad6470eb9ac3906ca83a23a5b09dd21428eb49b180ae0278a5dbf5fe9c1581899addba4e0dca11e16584e75c6ff44c62f4958dae5597991

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
